apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: reference-api
    app.kubernetes.io/name: argocd-release-details
  name: reference-api
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app.kubernetes.io/component: reference-api
  type: ClusterIP
