# see https://github.com/grpc-ecosystem/grpc-gateway/blob/main/.github/workflows/release.yml
name: release

on:
  push:
    tags:
      - 'v*'
env:
  # If set in the repo env vars it will use this tag to build the release notes.
  # Useful when creating a release tag after a release candidate tags phase.
  GORELEASER_PREVIOUS_TAG: ${{vars.GORELEASER_PREVIOUS_TAG}}

defaults:
  run:
    shell: bash

jobs:
  release:
    runs-on: ubuntu-24.04
    if: github.repository == 'mozilla/argocd-repository-details'
    name: Release
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # pin@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # pin@v4
        with:
          go-version: 1.22

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
